pipeline {
    agent any
    parameters { 
        booleanParam(name: "FORCE_INIT", defaultValue: false) 
        booleanParam(name: "FORCE_DESTROY", defaultValue: false)
    }
    stages {
        stage("load config") {
            steps {
                load "jkenvs/${JOB_NAME}.groovy"
                dir("jkconfigs") {
                    git(
                        url: "$INFRA_PRODUCTION_CONFIG_URL"
                    )
                    load "config.groovy"
                } 
                sh "mv jkconfigs/terraform.tfvars ."
            }
        }
        stage("Init") {
            when {
                anyOf {
                    equals(actual: currentBuild.number, expected: 1) 
                    expression {
                        return params.FORCE_INIT
                        
                   }
                }
            }
            steps {
                sh "terraform init "
            }
        }
        stage("Deploy") {
            when {
                expression { 
                    return !params.FORCE_DESTROY
                }
            }
            steps {
                sh "terraform apply -auto-approve"
            }
        }
        stage("Destroy") {
            when {
                expression { 
                    return params.FORCE_DESTROY
                }
            }
            steps {
                sh "terraform destroy -auto-approve"
            }
        }        
   }
}
